#!/bin/sh

source ../.common

#export WPA_SUPPLICANT_OUTPUT_PATH=${OUTPUT_PATH}/${WPA_SUPPLICANT}

#export OPENSSL_OUTPUT_PATH=${OUTPUT_PATH}/${OPENSSL}
export OPENSSL_OUTPUT_PATH=${OUTPUT_PATH}/${WPA_SUPPLICANT}


make_wpa_supplicant
